### PR TITLE
Added Profiles, Company and edited user creation

### PR DESCRIPTION
**Pull request by ellispax**
Check this one out, for profiles and company. More logic to follow.
As for comments i will try my best to put as much as i can when i can.

### CODE REVIEW

**Review by mcsamuelshoko — APPROVED** [review]
review complete

**Comment by mcsamuelshoko** [comment]
can you add a `.gitignore` and put the `pycache` files, should've informed you before the `merge conflict` , here is a [link to an example](https://stackoverflow.com/questions/3719243/best-practices-for-adding-gitignore-file-for-python-projects)

**Comment by ellispax** [comment]
Okay will check that out later and fix

**Comment by mcsamuelshoko** [comment]
let me get some sleep then i'll attend to the merge conflict in the morning, or you can attend to it if you're already awake by the time i wake up.
- an easy fix is for you to add a `.gitignore` file

**Pull request merged**
